# 📘 Notebook - Embeddings From Scratch

## 🎯 Objective

In this notebook, we'll understand how token IDs are converted into dense vector representations before entering the Transformer.

By the end of this notebook, you'll understand:

- Why Token IDs are not enough
- One-Hot Encoding
- Dense Embeddings
- Embedding Matrix
- Embedding Lookup
- Build an Embedding Layer From Scratch
- Cosine Similarity
- Learned Embeddings
- nn.Embedding

# Imports

In [1]:
import torch

# Token IDs

In [2]:
token_ids = [0, 1, 2, 3]

print(token_ids)

[0, 1, 2, 3]


# Why Can't We Feed IDs Directly?

In [3]:
token_ids = torch.tensor([0, 1, 2, 3])
print(token_ids)

tensor([0, 1, 2, 3])


# Visualizing the Problem

In [4]:
vocab = {
    "I": 0,
    "love": 1,
    "learning": 2,
    "AI": 3
}
for word, idx in vocab.items():
    print(f"{word} --> {idx}")

I --> 0
love --> 1
learning --> 2
AI --> 3


# What Do We Actually Need?

In [5]:
print("Token IDs are labels.")
print("Transformers need numerical representations containing meaning.")

Token IDs are labels.
Transformers need numerical representations containing meaning.


# What is One-Hot Encoding?

In [6]:
vocab = {
    "I": 0,
    "love": 1,
    "learning": 2,
    "AI": 3
}
print(vocab)

{'I': 0, 'love': 1, 'learning': 2, 'AI': 3}


# One-Hot Vector for "I"

In [7]:
one_hot = [1, 0, 0, 0]

print(one_hot)

[1, 0, 0, 0]


# One-Hot Vector for "love"`

In [8]:
one_hot = [0, 1, 0, 0]

print(one_hot)

[0, 1, 0, 0]


# One-Hot Vector for "learning"

In [9]:
one_hot = [0, 0, 1, 0]

print(one_hot)

[0, 0, 1, 0]


# One-Hot Vector for "AI"

In [10]:
one_hot = [0, 0, 0, 1]

print(one_hot)

[0, 0, 0, 1]


# Build One-Hot Automatically

In [11]:
vocab_size = len(vocab)

for word, idx in vocab.items():

    vector = [0] * vocab_size

    vector[idx] = 1

    print(word, "->", vector)

I -> [1, 0, 0, 0]
love -> [0, 1, 0, 0]
learning -> [0, 0, 1, 0]
AI -> [0, 0, 0, 1]


# Visualizing One-Hot Matrix

In [12]:
one_hot_matrix = []

for word, idx in vocab.items():

    vector = [0] * len(vocab)

    vector[idx] = 1

    one_hot_matrix.append(vector)

for row in one_hot_matrix:
    print(row)

[1, 0, 0, 0]
[0, 1, 0, 0]
[0, 0, 1, 0]
[0, 0, 0, 1]


# The First Problem

In [14]:
print("Vector for I :", one_hot_matrix[0])
print("Vector for AI :", one_hot_matrix[3])

Vector for I : [1, 0, 0, 0]
Vector for AI : [0, 0, 0, 1]


# Imagine a Vocabulary of 50,000 Words--every single word needs a vector of length 50,000,This wastes a huge amount of memory

In [15]:
print("Problem 1 -> Huge vectors")
print("Problem 2 -> No semantic meaning")

Problem 1 -> Huge vectors
Problem 2 -> No semantic meaning


# What is an Embedding?

In [16]:
word = "AI"

embedding = [0.42, -0.15, 0.88, 0.31]

print("Word:", word)
print("Embedding:", embedding)

Word: AI
Embedding: [0.42, -0.15, 0.88, 0.31]


# Multiple Word Embeddings

In [17]:
embeddings = {
    "I": [0.11, 0.42, -0.30, 0.25],
    "love": [0.60, -0.20, 0.71, -0.40],
    "learning": [0.32, 0.81, -0.15, 0.53],
    "AI": [0.42, -0.15, 0.88, 0.31]
}

for word, vector in embeddings.items():
    print(f"{word} --> {vector}")

I --> [0.11, 0.42, -0.3, 0.25]
love --> [0.6, -0.2, 0.71, -0.4]
learning --> [0.32, 0.81, -0.15, 0.53]
AI --> [0.42, -0.15, 0.88, 0.31]


# Embedding Dimension

In [18]:
embedding_dimension = len(embeddings["AI"])
print("Embedding Dimension:", embedding_dimension)

Embedding Dimension: 4


# Embedding Matrix

In [19]:
embedding_matrix = [
    [0.11, 0.42, -0.30, 0.25],
    [0.60, -0.20, 0.71, -0.40],
    [0.32, 0.81, -0.15, 0.53],
    [0.42, -0.15, 0.88, 0.31]
]

for row in embedding_matrix:
    print(row)

[0.11, 0.42, -0.3, 0.25]
[0.6, -0.2, 0.71, -0.4]
[0.32, 0.81, -0.15, 0.53]
[0.42, -0.15, 0.88, 0.31]


# Shape of the Matrix

In [20]:
rows = len(embedding_matrix)
columns = len(embedding_matrix[0])
print("Rows:", rows)
print("Columns:", columns)

Rows: 4
Columns: 4


# Embedding Lookup

In [21]:
token_id = 3
embedding = embedding_matrix[token_id]
print(embedding)

[0.42, -0.15, 0.88, 0.31]


# Random Initialization

In [22]:
import random
vocab_size = 4
embedding_dim = 5
embedding_matrix = []
for _ in range(vocab_size):
    row = []
    for _ in range(embedding_dim):
        row.append(round(random.uniform(-1, 1), 2))
    embedding_matrix.append(row)
for row in embedding_matrix:
    print(row)

[0.57, -0.8, 0.94, -0.58, 0.07]
[0.97, -0.4, 0.97, -0.25, -0.23]
[-0.79, -0.09, -0.44, 0.53, -0.54]
[-0.79, 0.13, 0.61, -0.05, 0.8]


# Assign Words to Rows

In [23]:
vocab = {
    "I": 0,
    "love": 1,
    "learning": 2,
    "AI": 3
}
for word, idx in vocab.items():
    print(word, "->", embedding_matrix[idx])

I -> [0.57, -0.8, 0.94, -0.58, 0.07]
love -> [0.97, -0.4, 0.97, -0.25, -0.23]
learning -> [-0.79, -0.09, -0.44, 0.53, -0.54]
AI -> [-0.79, 0.13, 0.61, -0.05, 0.8]


# Build Our Own Embedding Layer

In [24]:
class MyEmbedding:
    def __init__(self, embedding_matrix):
        self.embedding_matrix = embedding_matrix
    def forward(self, token_ids):
        embeddings = []
        for token in token_ids:
            embeddings.append(self.embedding_matrix[token])
        return embeddings

# Create Our Layer

In [25]:
layer = MyEmbedding(embedding_matrix)

In [26]:
token_ids = [0, 1, 2, 3]
output = layer.forward(token_ids)
for embedding in output:
    print(embedding)

[0.57, -0.8, 0.94, -0.58, 0.07]
[0.97, -0.4, 0.97, -0.25, -0.23]
[-0.79, -0.09, -0.44, 0.53, -0.54]
[-0.79, 0.13, 0.61, -0.05, 0.8]


# Compare with PyTorch

In [27]:
import torch
import torch.nn as nn

embedding = nn.Embedding(
    num_embeddings=4,
    embedding_dim=5
)

print(embedding.weight)

Parameter containing:
tensor([[-1.3750,  0.3042,  1.3477,  0.7253,  0.9359],
        [-0.6672, -0.7421, -1.0812, -0.1056,  0.2140],
        [ 1.9946, -0.8148, -0.3405,  0.3684,  0.1091],
        [ 1.5223,  1.1808,  0.5871, -0.3330, -1.4711]], requires_grad=True)


# How Embeddings Learn

# Initial Embeddings

In [28]:
import torch
import torch.nn as nn
embedding = nn.Embedding(
    num_embeddings=4,
    embedding_dim=3
)
print("Initial Embedding Matrix:\n")
print(embedding.weight)

Initial Embedding Matrix:

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.
Parameter containing:
tensor([[-0.7030,  0.2615, -0.7866],
        [-1.3037, -0.3117,  0.3152],
        [ 0.7913, -0.1837,  1.5432],
        [ 0.8849, -1.9130,  0.4121]], requires_grad=True)


In [29]:
print("During training:")
print("Forward Pass")
print("↓")
print("Loss")
print("↓")
print("Backpropagation")
print("↓")
print("Gradient Descent")
print("↓")
print("Updated Embeddings")

During training:
Forward Pass
↓
Loss
↓
Backpropagation
↓
Gradient Descent
↓
Updated Embeddings


# Cosine Similarity

# why compare embeddings?

In [1]:
embedding_ai = [0.42, -0.15, 0.88, 0.31]
embedding_python = [0.39, -0.18, 0.91, 0.29]
embedding_car = [-0.72, 0.64, -0.11, 0.48]
print("AI      :", embedding_ai)
print("Python  :", embedding_python)
print("Car     :", embedding_car)

AI      : [0.42, -0.15, 0.88, 0.31]
Python  : [0.39, -0.18, 0.91, 0.29]
Car     : [-0.72, 0.64, -0.11, 0.48]


# convert to tensors 

In [2]:
import torch
ai = torch.tensor(embedding_ai)
python = torch.tensor(embedding_python)
car = torch.tensor(embedding_car)

# cosine similarity 
(How similar the directions of two vectors are.)

In [3]:
cosine = torch.nn.CosineSimilarity(dim=0)

In [4]:
similarity=cosine(ai,python)
print(similarity.item())

0.9986482858657837


In [5]:
similarity = cosine(ai, car)
print("Similarity:", similarity.item())

Similarity: -0.3096150755882263
