## 📌 Step 1: Import NumPy

### Why?
- Used for matrix operations.
- Required for implementing Multi-Head Attention.

### Remember
- Multi-Head Attention is built using matrix multiplication.

In [1]:
import numpy as np 
print("Numpy Version:",np.__version__)

Numpy Version: 2.4.6


## 📌 Step 2: Create Embedding Matrix

### Why?
- Convert words into numerical vectors.
- Every attention head receives the same embeddings.

### Remember
- Input is shared by all attention heads.

In [2]:
X = np.array([
    [1.0, 0.0],
    [0.5, 1.0],
    [1.0, 1.0]
])

print("Embedding Matrix")
print(X)
print("\nShape:", X.shape)

Embedding Matrix
[[1.  0. ]
 [0.5 1. ]
 [1.  1. ]]

Shape: (3, 2)


## 📌 Step 3: Create Weights for Head 1

### Why?
- Each head has its own Wq, Wk and Wv.
- These weights learn different relationships.

### Remember
- Different heads = Different weight matrices.

In [4]:
Wq1 = np.array([
    [2,1],
    [1,2]
])

Wk1 = np.array([
    [1,0],
    [0,1]
])

Wv1 = np.array([
    [1,2],
    [2,1]
])

## 📌 Step 4: Create Weights for Head 2

### Why?
- Head 2 should learn a different representation.
- Therefore it uses different trainable weights.

### Remember
- Head 1 and Head 2 never share weights.

In [5]:
Wq2 = np.array([
    [1,2],
    [2,1]
])

Wk2 = np.array([
    [2,0],
    [1,1]
])

Wv2 = np.array([
    [2,1],
    [1,2]
])

## 📌 Step 5: Compute Q, K and V for Head 1

### Formula

Q₁ = X × Wq₁

K₁ = X × Wk₁

V₁ = X × Wv₁

### Remember
- Head 1 processes the sentence independently.

In [6]:
Q1 = X @ Wq1
K1 = X @ Wk1
V1 = X @ Wv1

## 📌 Step 6: Compute Q, K and V for Head 2

### Formula

Q₂ = X × Wq₂

K₂ = X × Wk₂

V₂ = X × Wv₂

### Remember
- Same input.
- Different learned representation.

In [7]:
Q2 = X @ Wq2
K2 = X @ Wk2
V2 = X @ Wv2

In [8]:
scores1 = Q1 @ K1.T
scores1 = scores1 / np.sqrt(K1.shape[1])

def softmax(x):
    exp = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return exp / np.sum(exp, axis=-1, keepdims=True)

attention1 = softmax(scores1)

output1 = attention1 @ V1

print(output1)

[[2.3793623  2.50348984]
 [2.64661132 2.60104011]
 [2.71839577 2.68208152]]


In [9]:
scores2 = Q2 @ K2.T
scores2 = scores2 / np.sqrt(K2.shape[1])

attention2 = softmax(scores2)

output2 = attention2 @ V2

print(output2)

[[2.61998512 2.69851311]
 [2.82493471 2.86111099]
 [2.88164541 2.92181937]]


## 📌 Step 9: Concatenate Head Outputs

### Why?
- Combine information learned by different heads.

### Formula

Output = Concat(Head₁, Head₂)

### Remember
- Concatenation joins features.
- It does not add them.

In [10]:
multi_head_output = np.concatenate((output1, output2), axis=1)

print(multi_head_output)

print("\nShape:", multi_head_output.shape)

[[2.3793623  2.50348984 2.61998512 2.69851311]
 [2.64661132 2.60104011 2.82493471 2.86111099]
 [2.71839577 2.68208152 2.88164541 2.92181937]]

Shape: (3, 4)


In [11]:
Wo = np.array([
    [1,0],
    [0,1],
    [1,1],
    [2,1]
])

final_output = multi_head_output @ Wo

print(final_output)

[[10.39637365  7.82198807]
 [11.193768    8.28708581]
 [11.44367992  8.4855463 ]]
