In [1]:
import torch
import math

In [2]:
sentence1 = "Dog bites man"
sentence2 = "Man bites dog"
print(sentence1)
print(sentence2)

Dog bites man
Man bites dog


In [3]:
vector = torch.tensor([2.0, 1.0])
print(vector)

tensor([2., 1.])


In [4]:
rotated_vector = torch.tensor([
    -vector[1],
     vector[0]
])
print(rotated_vector)

tensor([-1.,  2.])


In [5]:
print(torch.norm(vector))
print(torch.norm(rotated_vector))

tensor(2.2361)
tensor(2.2361)


In [6]:
query = torch.tensor([2.0, 1.0])
key = torch.tensor([1.5, 2.5])
print("Query:", query)
print("Key:", key)

Query: tensor([2., 1.])
Key: tensor([1.5000, 2.5000])


In [8]:
def rotate(vector):
    return torch.tensor([
        -vector[1],
         vector[0]
    ])

In [9]:
rotated_query = rotate(query)
rotated_key = rotate(key)
print("Rotated Query:", rotated_query)
print("Rotated Key:", rotated_key)

Rotated Query: tensor([-1.,  2.])
Rotated Key: tensor([-2.5000,  1.5000])


In [10]:
original_score = torch.dot(query, key)
rotated_score = torch.dot(rotated_query, rotated_key)
print("Original Attention Score:", original_score.item())
print("RoPE Attention Score:", rotated_score.item())

Original Attention Score: 5.5
RoPE Attention Score: 5.5


In [11]:
position = 2
theta = position * (math.pi / 4)
print("Theta (radians):", theta)
print("Theta (degrees):", math.degrees(theta))

Theta (radians): 1.5707963267948966
Theta (degrees): 90.0


In [12]:
rotation_matrix = torch.tensor([
    [math.cos(theta), -math.sin(theta)],
    [math.sin(theta),  math.cos(theta)]
])
print(rotation_matrix)

tensor([[ 6.1232e-17, -1.0000e+00],
        [ 1.0000e+00,  6.1232e-17]])


In [13]:
vector = torch.tensor([2.0, 1.0])
rotated_vector = rotation_matrix @ vector
print("Original:", vector)
print("Rotated :", rotated_vector)

Original: tensor([2., 1.])
Rotated : tensor([-1.,  2.])
