## 📌 Step 1: Import NumPy

### Why?
- NumPy is used for matrix and vector operations.
- Transformers rely heavily on matrix multiplication.

### Output
- Displays the installed NumPy version.

In [2]:
import numpy as np
print("Numpy Version:",np.__version__)

Numpy Version: 2.4.6


## 📌 Step 2: Create Embeddings

### Why?
- Computers understand numbers, not words.
- Every word is converted into an embedding vector.
- Here we manually create embeddings for learning.

### Remember
Rows → Words

Columns → Embedding Dimensions

In [3]:
X = np.array([
    [1.0, 0.0],      # I
    [0.5, 1.0],      # love
    [1.0, 1.0]       # AI
])
print("Embedding Matrix:")
print(X)
print("\nShape:",X.shape)

Embedding Matrix:
[[1.  0. ]
 [0.5 1. ]
 [1.  1. ]]

Shape: (3, 2)


## 📌 Step 3: Create Wq, Wk and Wv

### Why?
- Wq creates Queries.
- Wk creates Keys.
- Wv creates Values.
- These are trainable parameters.

### Formula
Q = X × Wq

K = X × Wk

V = X × Wv

In [4]:
Wq = np.array([
    [2,1],
    [1,2]
])

Wk = np.array([
    [1,0],
    [0,1]
])

Wv = np.array([
    [1,2],
    [2,1]
])

print("Wq")
print(Wq)

print("\nWk")
print(Wk)

print("\nWv")
print(Wv)

Wq
[[2 1]
 [1 2]]

Wk
[[1 0]
 [0 1]]

Wv
[[1 2]
 [2 1]]


## 📌 Step 4: Generate Query Matrix (Q)

### Why?
- Convert embeddings into Query vectors.
- Query represents what each word is searching for.

### Formula
Q = X × Wq

### Remember
- Q is **not** attention.
- Every word gets its own Query vector.

In [9]:
Q = X @ Wq
print("Queries")
print(Q)
print("\nShape:", Q.shape)

Queries
[[2.  1. ]
 [2.  2.5]
 [3.  3. ]]

Shape: (3, 2)


## 📌 Step 5: Generate Key Matrix (K)

### Why?
- Convert embeddings into Key vectors.
- Keys represent the information each word contains.

### Formula
K = X × Wk

### Remember
- Every Query is compared with every Key.

In [10]:
K = X @ Wk

print("Keys")
print(K)

print("\nShape:", K.shape)

Keys
[[1.  0. ]
 [0.5 1. ]
 [1.  1. ]]

Shape: (3, 2)


## 📌 Step 6: Generate Value Matrix (V)

### Why?
- Convert embeddings into Value vectors.
- Values contain the information passed to the output.

### Formula
V = X × Wv

### Remember
- Attention decides **which Values** should contribute more.

In [11]:
V = X @ Wv

print("Values")
print(V)

print("\nShape:", V.shape)

Values
[[1.  2. ]
 [2.5 2. ]
 [3.  3. ]]

Shape: (3, 2)


## 📌 Step 7: Compute Attention Scores

### Why?
- Measure similarity between Queries and Keys.

### Formula
Scores = Q × Kᵀ

### Remember
- Higher score → Higher similarity.
- Scores are **not probabilities**.

In [12]:
scores = Q @ K.T

print("Attention Scores")
print(scores)

print("\nShape:", scores.shape)

Attention Scores
[[2.  2.  3. ]
 [2.  3.5 4.5]
 [3.  4.5 6. ]]

Shape: (3, 3)


## 📌 Step 8: Scale Attention Scores

### Why?
- Prevent very large attention scores.
- Helps Softmax produce stable probabilities.

### Formula
Scaled Scores = Scores / √dk

### Remember
dk = Key dimension

In [13]:
dk = K.shape[1]

print("dk =", dk)

scaled_scores = scores / np.sqrt(dk)

print("\nScaled Scores")
print(scaled_scores)

dk = 2

Scaled Scores
[[1.41421356 1.41421356 2.12132034]
 [1.41421356 2.47487373 3.18198052]
 [2.12132034 3.18198052 4.24264069]]


## 📌 Step 9: Apply Softmax

### Why?
- Convert attention scores into probabilities.

### Remember
- Each row sums to 1.
- Higher probability → More attention.

In [14]:
def softmax(x):
    exp = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return exp / np.sum(exp, axis=-1, keepdims=True)

attention = softmax(scaled_scores)

print("Attention Weights")
print(attention)

Attention Weights
[[0.24825508 0.24825508 0.50348984]
 [0.10260583 0.29635406 0.60104011]
 [0.08176333 0.23615515 0.68208152]]


In [15]:
print(attention.sum(axis=1))

[1. 1. 1.]


## 📌 Step 10: Compute Final Output

### Why?
- Generate context-aware word representations.

### Formula
Output = Attention × V

### Remember
- Values are weighted by attention probabilities.
- This is the final output of Self-Attention.

In [16]:
output = attention @ V

print("Final Output")
print(output)

print("\nShape:", output.shape)

Final Output
[[2.3793623  2.50348984]
 [2.64661132 2.60104011]
 [2.71839577 2.68208152]]

Shape: (3, 2)
