In [12]:
import torch
import torch.nn.functional as F

In [13]:
vocab = {
    0: "I",
    1: "love",
    2: "learning",
    3: "AI",
    4: ".",
    5: "Python",
    6: "because",
    7: "it",
    8: "is",
    9: "fun"
}

In [14]:
logits = torch.tensor([
    2.1,
    0.8,
    4.5,
    3.2,
    0.5,
    2.7,
    1.0,
    0.4,
    1.6,
    2.2
])
print(logits)

tensor([2.1000, 0.8000, 4.5000, 3.2000, 0.5000, 2.7000, 1.0000, 0.4000, 1.6000,
        2.2000])


In [15]:
probabilities=F.softmax(logits,dim=0)
print(probabilities)

tensor([0.0511, 0.0139, 0.5638, 0.1537, 0.0103, 0.0932, 0.0170, 0.0093, 0.0310,
        0.0565])


In [16]:
for i,p in enumerate(probabilities):
    print(f"{vocab[i]} : {p.item():.3f}")

I : 0.051
love : 0.014
learning : 0.564
AI : 0.154
. : 0.010
Python : 0.093
because : 0.017
it : 0.009
is : 0.031
fun : 0.057


In [17]:
next_token=torch.argmax(probabilities)
print("predicted token:",vocab[next_token.item()])

predicted token: learning


In [18]:
temperature=0.7
scaled_logits=logits/temperature
probs=F.softmax(scaled_logits,dim=0)
print(probs)

tensor([0.0243, 0.0038, 0.7484, 0.1168, 0.0025, 0.0572, 0.0050, 0.0021, 0.0119,
        0.0280])


In [19]:
next_token = torch.multinomial(probs, num_samples=1)

print(vocab[next_token.item()])

learning


In [20]:
k = 3
topk_probs, topk_indices = torch.topk(probabilities, k)
topk_probs = topk_probs / topk_probs.sum()
sampled = torch.multinomial(topk_probs, 1)
next_token = topk_indices[sampled]
print(vocab[next_token.item()])

learning


In [21]:
sorted_probs, sorted_indices = torch.sort(probabilities, descending=True)

cumulative_probs = torch.cumsum(sorted_probs, dim=0)

p = 0.90

mask = cumulative_probs <= p

filtered_probs = sorted_probs[mask]
filtered_indices = sorted_indices[mask]

filtered_probs = filtered_probs / filtered_probs.sum()

sampled = torch.multinomial(filtered_probs, 1)

next_token = filtered_indices[sampled]

print(vocab[next_token.item()])

AI


In [22]:
generated = []

for _ in range(5):

    probs = F.softmax(logits, dim=0)

    token = torch.multinomial(probs, 1)

    generated.append(vocab[token.item()])

print("Generated Sentence:")
print(" ".join(generated))

Generated Sentence:
I learning Python AI learning


In [23]:
methods = {
    "Greedy": "Highest probability only",
    "Temperature": "Controls randomness",
    "Top-k": "Choose among top k tokens",
    "Top-p": "Choose from smallest set whose cumulative probability reaches p"
}

for method, description in methods.items():
    print(f"{method} -> {description}")

Greedy -> Highest probability only
Temperature -> Controls randomness
Top-k -> Choose among top k tokens
Top-p -> Choose from smallest set whose cumulative probability reaches p
